---
- name: "PLAY 1: CREATE SSE HUB"
  hosts: meraki
  connection: local
  gather_facts: false
  collections:
    - cisco.meraki

  vars:
    meraki_headers:
      Content-Type: "application/json"
      X-Cisco-Meraki-API-Key: "{{ meraki_key }}"

  tasks:

    - name: "TASK 1: Read VLAN data from Excel"
      command: python3 read_excel.py "Secure Connect Hub"
      args:
        chdir: ./scripts  # Specify the path to your Python script
      register: sse_data
      changed_when: false
      check_mode: no
      run_once: true

    - set_fact:
        sse_data: "{{ sse_data.stdout | from_json }}"

    - name: "TASK 2: Read SSE"
      uri:
        url: "{{baseUrl}}/organizations/{{organizationId}}/secureConnect/sites"
        method: GET
        body_format: json
        headers:
          Content-Type: application/json
          X-Cisco-Meraki-API-Key: "{{ meraki_key }}"
        status_code: [200, 201, 202]
        return_content: true
      register: result

    - name: "TASK 2: Configure SSE"
      uri:
        url: "{{baseUrl}}/organizations/{{organizationId}}/secureConnect/sites"
        method: POST
        body_format: json
        headers:
          Content-Type: application/json
          X-Cisco-Meraki-API-Key: "{{ meraki_key }}"
        status_code: [200, 201, 202]
        return_content: true
        body: |
          {
            "enrollments": [
              {
                "regionType": "{{ item.regionType }}",
                "siteId": "{{ result.json.data[0].id }}",
                "regionName": "{{ item.regionName }}"
              }
            ],
          }          
      with_items: "{{ sse_data }}"
