# Generated by Django 4.1.13 on 2024-05-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('serial_no', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Serial No.')),
                ('hostname', models.CharField(max_length=100, verbose_name='Hostname')),
                ('warmspare', models.BooleanField(default=False, verbose_name='Warmspare')),
                ('stp_root', models.BooleanField(default=False, verbose_name='Stp Root')),
            ],
            options={
                'db_table': 'mcdmerakiapp_device',
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('networkName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vlan_id', models.IntegerField()),
                ('vlan_name', models.CharField(max_length=100)),
                ('subnet', models.CharField(max_length=100)),
                ('gateway', models.CharField(max_length=100)),
                ('enable_dhcp', models.BooleanField(default=False)),
                ('lease_time', models.IntegerField()),
                ('reserved_ip_start', models.CharField(max_length=100)),
                ('reserved_ip_end', models.CharField(max_length=100)),
                ('dns_nameservers', models.CharField(max_length=100)),
                ('dhcp_option', models.CharField(max_length=100)),
                ('dhcp_type', models.CharField(max_length=100)),
                ('ntp_ip', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mcdmerakiapp_vlan',
            },
        ),
    ]
