# Generated by Django 4.1.13 on 2024-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdmerakiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=100)),
                ('authMode', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('ipAssignmentMode', models.CharField(max_length=100)),
                ('vlanId', models.IntegerField()),
                ('visible', models.BooleanField(default=False)),
                ('encryptionMode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mcdmerakiapp_wifi',
            },
        ),
        migrations.AlterField(
            model_name='vlan',
            name='lease_time',
            field=models.CharField(max_length=100),
        ),
    ]
